# Generated by Django 5.2.1 on 2025-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="item_pictures/"),
        ),
    ]
